apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: timedeal-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: timedeal-app  # HPA를 적용할 Deployment 이름
  minReplicas: 1        # 최소 Pod 수
  maxReplicas: 10       # 최대 Pod 수
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # CPU 사용률 50%를 목표로 자동 확장