apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-timedeal-app
  namespace: argocd
spec:
  project: timedealapp
  source:
    repoURL: 'https://github.com/strong2team/shoppingMall-eks.git'
    targetRevision: HEAD
    path: 'deployment'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true