apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: test-app
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-northeast-2:820242919524:secret:timdeal-env-GIq81O"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_USERNAME"
            objectAlias: "DB_USERNAME"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
          - path: "DB_URL"
            objectAlias: "DB_URL"
          - path: "DB_DRIVER_CLASS_NAME"
            objectAlias: "DB_DRIVER_CLASS_NAME"
          - path: "DB_TIMEDEAL_LOCAL_URL"
            objectAlias: "DB_TIMEDEAL_LOCAL_URL"
          - path: "DB_NAME"
            objectAlias: "DB_NAME"
          - path: "NAVER_CLIENT_ID"
            objectAlias: "NAVER_CLIENT_ID"
          - path: "NAVER_CLIENT_SECRET"
            objectAlias: "NAVER_CLIENT_SECRET"
          - path: "AWS_S3_BUCKET"
            objectAlias: "AWS_S3_BUCKET"
          - path: "AWS_ACCESS_KEY"
            objectAlias: "AWS_ACCESS_KEY"
          - path: "AWS_SECRET_KEY"
            objectAlias: "AWS_SECRET_KEY"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "AWS_S3_IMAGE_NAME"
            objectAlias: "AWS_S3_IMAGE_NAME"
          - path: "AWS_LAMBDA_TIMEDEAL_UPDATE_ARN"
            objectAlias: "AWS_LAMBDA_TIMEDEAL_UPDATE_ARN"
          - path: "TIMEDEAL_TABLE_QUEUE_NAME"
            objectAlias: "TIMEDEAL_TABLE_QUEUE_NAME"
          - path: "DB_HOST"
            objectAlias: "DB_HOST"
          - path: "DB_PORT"
            objectAlias: "DB_PORT"
          - path: "REDIS_HOST"
            objectAlias: "REDIS_HOST"
          - path: "REDIS_PORT"
            objectAlias: "REDIS_PORT"
          - path: "AWS_CLOUDFRONT_CNAME"
            objectAlias: "AWS_CLOUDFRONT_CNAME"
          - path: "AWS_S3_IMAGE_FOLDER"
            objectAlias: "AWS_S3_IMAGE_FOLDER"
          - path: "DB_PROD_URL"
            objectAlias: "DB_PROD_URL"
          - path: "NAVER_API_URL"
            objectAlias: "NAVER_API_URL"
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
  secretObjects:
  - secretName: aws-secrets
    type: Opaque
    data:
      - objectName: "DB_USERNAME"
        key: "DB_USERNAME"
      - objectName: "DB_PASSWORD"
        key: "DB_PASSWORD"
      - objectName: "DB_URL"
        key: "DB_URL"
      - objectName: "DB_DRIVER_CLASS_NAME"
        key: "DB_DRIVER_CLASS_NAME"
      - objectName: "DB_TIMEDEAL_LOCAL_URL"
        key: "DB_TIMEDEAL_LOCAL_URL"
      - objectName: "DB_NAME"
        key: "DB_NAME"
      - objectName: "NAVER_CLIENT_ID"
        key: "NAVER_CLIENT_ID"
      - objectName: "NAVER_CLIENT_SECRET"
        key: "NAVER_CLIENT_SECRET"
      - objectName: "AWS_S3_BUCKET"
        key: "AWS_S3_BUCKET"
      - objectName: "AWS_ACCESS_KEY"
        key: "AWS_ACCESS_KEY"
      - objectName: "AWS_SECRET_KEY"
        key: "AWS_SECRET_KEY"
      - objectName: "AWS_REGION"
        key: "AWS_REGION"
      - objectName: "AWS_S3_IMAGE_NAME"
        key: "AWS_S3_IMAGE_NAME"
      - objectName: "AWS_LAMBDA_TIMEDEAL_UPDATE_ARN"
        key: "AWS_LAMBDA_TIMEDEAL_UPDATE_ARN"
      - objectName: "TIMEDEAL_TABLE_QUEUE_NAME"
        key: "TIMEDEAL_TABLE_QUEUE_NAME"
      - objectName: "DB_HOST"
        key: "DB_HOST"
      - objectName: "DB_PORT"
        key: "DB_PORT"
      - objectName: "REDIS_HOST"
        key: "REDIS_HOST"
      - objectName: "REDIS_PORT"
        key: "REDIS_PORT"
      - objectName: "AWS_CLOUDFRONT_CNAME"
        key: "AWS_CLOUDFRONT_CNAME"
      - objectName: "AWS_S3_IMAGE_FOLDER"
        key: "AWS_S3_IMAGE_FOLDER"
      - objectName: "DB_PROD_URL"
        key: "DB_PROD_URL"
      - objectName: "NAVER_API_URL"
        key: "NAVER_API_URL"
      - objectName: "username"
        key: "username"
      - objectName: "password"
        key: "password"
