apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-store-csi-driver-secret-creator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-store-csi-driver-secret-creator-binding
subjects:
  - kind: ServiceAccount
    name: secrets-store-csi-driver
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: secrets-store-csi-driver-secret-creator
  apiGroup: rbac.authorization.k8s.io
